In [33]:
import numpy as np
import pandas as pd
import os

In [34]:
# test with csv
mat1 = pd.read_csv('datasets-b3/APER3.csv')
mat2 = pd.read_csv('datasets-b3/BEES3.csv')

In [35]:
var = []
var.append(('BEES3', 'BEES3', 0.555))
var.append(('BEES3', 'BEES3', 0.555))
var.append(('BEES3', 'BEES3', 0.555))
var.append(('BEES3', 'BEES3', 0.555))
var

[('BEES3', 'BEES3', 0.555),
 ('BEES3', 'BEES3', 0.555),
 ('BEES3', 'BEES3', 0.555),
 ('BEES3', 'BEES3', 0.555)]

In [36]:
type(var)
type(var[0])

tuple

In [37]:
var2 = {}

In [38]:
type(var2)

dict

In [56]:
data = pd.read_csv('datasets/data.csv', index_col=0)
data

,Data,AALR3,AAPL34,ABCB4,ABEV3,ADHM3,AGRO3,ALPA3,ALPA4,ALSO3,...,VLID3,VULC3,VVAR3,WEGE3,WHRL4,WIZS3,WSON33,XBOV11,XPIE11,YDUQ3
0,02/01/2020,19.00,121.34,20.30,19.20,2.48,19.25,26.80,32.58,50.01,...,17.04,9.00,11.73,35.24,10.27,14.35,46.00,116.30,102.98,46.75
1,03/01/2020,19.00,121.58,20.75,18.93,2.35,19.45,27.19,32.58,51.42,...,16.81,8.83,11.48,34.79,10.10,14.35,46.01,115.51,102.98,45.77
2,06/01/2020,18.99,122.18,20.62,19.02,2.42,19.46,26.66,32.07,51.07,...,17.55,8.98,11.48,34.88,10.03,15.13,46.33,114.70,101.00,46.65
3,07/01/2020,18.94,122.48,20.36,19.06,2.37,19.40,26.65,32.80,50.47,...,17.23,8.99,11.65,35.15,9.72,15.97,46.20,114.47,108.00,45.78
4,08/01/2020,18.97,123.51,20.30,18.97,2.36,19.20,26.77,33.16,52.00,...,16.82,8.99,11.60,33.82,9.94,14.90,46.49,114.09,105.00,45.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,30/04/2020,10.49,159.09,14.29,11.34,2.48,20.50,22.21,27.39,27.91,...,8.92,4.22,9.18,39.94,6.48,9.12,28.99,79.19,83.99,30.35
82,04/05/2020,9.75,161.70,13.39,11.76,2.38,20.65,21.16,26.40,26.20,...,8.78,4.23,9.50,39.84,6.47,8.66,27.99,77.62,82.01,28.53
83,05/05/2020,9.52,166.50,13.41,11.94,2.38,20.90,21.90,26.38,25.15,...,8.49,4.11,9.70,39.01,6.55,8.20,28.89,78.26,84.49,28.84
84,06/05/2020,9.60,172.79,13.04,11.83,2.38,21.10,21.50,25.47,24.41,...,8.59,4.15,10.01,38.83,6.43,8.04,30.59,77.80,90.00,28.04
85,07/05/2020,9.24,177.87,12.68,11.54,2.34,21.47,21.55,24.87,22.70,...,8.00,3.97,9.74,39.09,6.21,7.70,30.50,77.27,87.99,26.78

In [96]:
rows = []
rows.append(["ABC","CDE",0.56663])
rows.append(["ABC","CDE",0.56663])

df = pd.DataFrame(rows, columns=['A', 'B', 'C'])
df

     A    B        C
0  ABC  CDE  0.56663
1  ABC  CDE  0.56663

In [98]:
len(rows)

2

In [85]:
data = pd.read_csv('datasets/data.csv', index_col=0)

,Data,AALR3,AAPL34,ABCB4,ABEV3,ADHM3,AGRO3,ALPA3,ALPA4,ALSO3,...,VLID3,VULC3,VVAR3,WEGE3,WHRL4,WIZS3,WSON33,XBOV11,XPIE11,YDUQ3
0,02/01/2020,19.00,121.34,20.30,19.20,2.48,19.25,26.80,32.58,50.01,...,17.04,9.00,11.73,35.24,10.27,14.35,46.00,116.30,102.98,46.75
1,03/01/2020,19.00,121.58,20.75,18.93,2.35,19.45,27.19,32.58,51.42,...,16.81,8.83,11.48,34.79,10.10,14.35,46.01,115.51,102.98,45.77
2,06/01/2020,18.99,122.18,20.62,19.02,2.42,19.46,26.66,32.07,51.07,...,17.55,8.98,11.48,34.88,10.03,15.13,46.33,114.70,101.00,46.65
3,07/01/2020,18.94,122.48,20.36,19.06,2.37,19.40,26.65,32.80,50.47,...,17.23,8.99,11.65,35.15,9.72,15.97,46.20,114.47,108.00,45.78
4,08/01/2020,18.97,123.51,20.30,18.97,2.36,19.20,26.77,33.16,52.00,...,16.82,8.99,11.60,33.82,9.94,14.90,46.49,114.09,105.00,45.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,30/04/2020,10.49,159.09,14.29,11.34,2.48,20.50,22.21,27.39,27.91,...,8.92,4.22,9.18,39.94,6.48,9.12,28.99,79.19,83.99,30.35
82,04/05/2020,9.75,161.70,13.39,11.76,2.38,20.65,21.16,26.40,26.20,...,8.78,4.23,9.50,39.84,6.47,8.66,27.99,77.62,82.01,28.53
83,05/05/2020,9.52,166.50,13.41,11.94,2.38,20.90,21.90,26.38,25.15,...,8.49,4.11,9.70,39.01,6.55,8.20,28.89,78.26,84.49,28.84
84,06/05/2020,9.60,172.79,13.04,11.83,2.38,21.10,21.50,25.47,24.41,...,8.59,4.15,10.01,38.83,6.43,8.04,30.59,77.80,90.00,28.04
85,07/05/2020,9.24,177.87,12.68,11.54,2.34,21.47,21.55,24.87,22.70,...,8.00,3.97,9.74,39.09,6.21,7.70,30.50,77.27,87.99,26.78

Data
AALR3
AAPL34
ABCB4
ABEV3
ADHM3
AGRO3
ALPA3
ALPA4
ALSO3
ALUP11
ALUP3
ALUP4
AMAR3
ANIM3
APER3
ARZZ3
ATOM3
AZUL4
B3SA3
BBAS3
BBDC3
BBDC4
BBRK3
BBSD11
BBSE3
BEEF3
BEES3
BEES4
BIDI11
BIDI3
BIDI4
BIOM3
BKBR3
BMEB4
BMGB4
BOBR4
BOVA11
BOVB11
BOVV11
BPAC11
BPAN4
BRAP3
BRAP4
BRAX11
BRDT3
BRFS3
BRKM3
BRKM5
BRML3
BRPR3
BRSR3
BRSR6
BSEV3
BTOW3
CAMB3
CAML3
CARD3
CCPR3
CCRO3
CEAB3
CESP3
CESP6
CGAS5
CGRA3
CGRA4
CIEL3
CMIG3
CMIG4
CNTO3
COCE5
COGN3
CPFE3
CPLE3
CPLE6
CRFB3
CRPG5
CSAN3
CSMG3
CSNA3
CTNM4
CVCB3
CYRE3
DIRR3
DIVO11
DMMO3
DTEX3
EALT4
ECOR3
EGIE3
ELET3
ELET6
EMAE4
EMBR3
ENAT3
ENBR3
ENEV3
ENGI11
ENGI3
ENGI4
EQPA3
EQTL3
EUCA3
EUCA4
EVEN3
EZTC3
FESA4
FIND11
FLRY3
FNAM11
FNOR11
FRAS3
FSRF11
GBIO33
GFSA3
GGBR3
GGBR4
GNDI3
GOAU3
GOAU4
GOLL4
GPIV33
GRND3
GUAR3
HAGA4
HAPV3
HBOR3
HGTX3
HYPE3
IDNT3
IDVL3
IDVL4
IGTA3
IRBR3
ITSA3
ITSA4
ITUB3
ITUB4
IVVB11
JBDU4
JBSS3
JHSF3
JPSA3
JSLG3
KEPL3
KLBN11
KLBN3
KLBN4
LAME3
LAME4
LCAM3
LEVE3
LIGT3
LINX3
LLIS3
LOGG3
LOGN3
LPSB3
LREN3
MATB11
MDIA3
MEAL3
MGLU3
MILS3
MOVI3
MRFG3
MRVE3
MTSA4
MULT3
MYPK3
NEOE3
NTCO3
ODPV3
OFSA3
OMGE3
PARD3
PETR3
PETR4
PFRM3
PIBB11
PINE4
PMAM3
POMO3
POMO4
POSI3
PPLA11
PRIO3
PSSA3
PTBL3
PTNT4
QUAL3
RADL3
RAIL3
RANI3
RANI4
RAPT3
RAPT4
RCSL3
RCSL4
RDNI3
RENT3
RLOG3
ROMI3
RSID3
SANB11
SANB3
SANB4
SAPR11
SAPR3
SAPR4
SBSP3
SCAR3
SEER3
SGPS3
SHOW3
SHUL4
SLCE3
SMAL11
SMLS3
SMTO3
SPXI11
SQIA3
STBP3
SULA11
SULA3
SUZB3
TAEE11
TAEE3
TAEE4
TASA3
TASA4
TCSA3
TECN3
TELB4
TEND3
TESA3
TGMA3
TIET11
TIET3
TIET4
TIMP3
TOTS3
TRIS3
TRPL3
TRPL4
TUPY3
UCAS3
UGPA3
UNIP3
UNIP6
USIM3
USIM5
VALE3
VIGT11
VIVA3
VIVT3
VIVT4
VLID3
VULC3
VVAR3
WEGE3
WHRL4
WIZS3
WSON33
XBOV11
XPIE11
YDUQ3